services:
  namenode:
    image: apache/hadoop:3.4.1
    restart: on-failure
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870/tcp
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

  datanode1:
    image: apache/hadoop:3.4.1
    restart: on-failure
    hostname: datanode1
    command: ["hdfs", "datanode"]
    env_file:
      - ./config

  datanode2:
    image: apache/hadoop:3.4.1
    restart: on-failure
    hostname: datanode2
    command: ["hdfs", "datanode"]
    env_file:
      - ./config

  datanode3:
    image: apache/hadoop:3.4.1
    restart: on-failure
    hostname: datanode3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
