services:
  zookeeper1:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper1
    hostname: zookeeper1
    ports:
      - 2181:2181/tcp
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper1_data:/data
      - .data/zookeeper1_log:/datalog

  zookeeper2:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper2
    hostname: zookeeper2
    ports:
      - 2182:2181/tcp
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper2_data:/data
      - .data/zookeeper2_log:/datalog

  zookeeper3:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper3
    hostname: zookeeper3
    ports:
      - 2183:2181/tcp
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper3_data:/data
      - .data/zookeeper3_log:/datalog

  namenode:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870/tcp
    env_file:
      - ./config
    volumes:
      - .data/namenode:/opt/namenode

  datanode1:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode1
    hostname: datanode1
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode1:/opt/data

  datanode2:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode2
    hostname: datanode2
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode2:/opt/data

  datanode3:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode3
    hostname: datanode3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode3:/opt/data
