services:
  namenode1:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-namenode1
    hostname: namenode1
    command: ["bash", "/opt/start_namenode1.sh"]
    ports:
      - 9871:9870/tcp
    env_file:
      - ./config
    volumes:
      - ./scripts/start_namenode1.sh:/opt/start_namenode1.sh:ro
      - .data/namenode1:/opt/namenode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3

  namenode2:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-namenode2
    hostname: namenode2
    command: ["bash", "/opt/start_namenode2.sh"]
    ports:
      - 9872:9870/tcp
    env_file:
      - ./config
    volumes:
      - ./scripts/start_namenode2.sh:/opt/start_namenode2.sh:ro
      - .data/namenode2:/opt/namenode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3

  namenode3:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-namenode3
    hostname: namenode3
    command: ["bash", "/opt/start_namenode3.sh"]
    ports:
      - 9873:9870/tcp
    env_file:
      - ./config
    volumes:
      - ./scripts/start_namenode3.sh:/opt/start_namenode3.sh:ro
      - .data/namenode3:/opt/namenode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
      - journalnode1
      - journalnode2
      - journalnode3

  journalnode1:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-journalnode1
    hostname: journalnode1
    command: ["hdfs", "journalnode"]
    env_file:
      - ./config
    volumes:
      - .data/journalnode1:/opt/journalnode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  journalnode2:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-journalnode2
    hostname: journalnode2
    command: ["hdfs", "journalnode"]
    env_file:
      - ./config
    volumes:
      - .data/journalnode2:/opt/journalnode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  journalnode3:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-journalnode3
    hostname: journalnode3
    command: ["hdfs", "journalnode"]
    env_file:
      - ./config
    volumes:
      - .data/journalnode3:/opt/journalnode
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

  datanode1:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode1
    hostname: datanode1
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode1:/opt/data
    depends_on:
      - namenode1
      - namenode2
      - namenode3

  datanode2:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode2
    hostname: datanode2
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode2:/opt/data
    depends_on:
      - namenode1
      - namenode2
      - namenode3

  datanode3:
    image: apache/hadoop:3.4.1
    restart: on-failure
    container_name: hdfs-datanode3
    hostname: datanode3
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    volumes:
      - .data/datanode3:/opt/data
    depends_on:
      - namenode1
      - namenode2
      - namenode3

  zookeeper1:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper1
    hostname: zookeeper1
    ports:
      - 2181:2181/tcp
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper1_data:/data
      - .data/zookeeper1_log:/datalog

  zookeeper2:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper2
    hostname: zookeeper2
    ports:
      - 2182:2181/tcp
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper2_data:/data
      - .data/zookeeper2_log:/datalog

  zookeeper3:
    image: zookeeper:3.9.3
    restart: on-failure
    container_name: hdfs-zookeeper3
    hostname: zookeeper3
    ports:
      - 2183:2181/tcp
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888;2181 server.2=zookeeper2:2888:3888;2181 server.3=zookeeper3:2888:3888;2181
    volumes:
      - .data/zookeeper3_data:/data
      - .data/zookeeper3_log:/datalog
